spring:
  application:
    name: demongfile
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:mem:muselock
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://muselock.us.auth0.com/
          audiences:
            - https://muselock/
media:
  location: mediafiles
server:
  servlet:
    context-path: /api
  port: 8080
similarity:
  url: http://0.0.0.0:8001