spring:
  application:
    name: demongfile
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/nombre_base_datos
    username: tu_usuario
    password: tu_contraseña
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/
media:
  location: mediafiles
server:
  servlet:
    context-path: /api
  port: 4200
similarity:
  url: http://localhost:9000